#!/usr/bin/env python3
"""Prepare human-readable annotation workbook from reference validation sample."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

_SCRIPTS = Path(__file__).resolve().parents[1]
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from lifecycle.corpus_paths import configure

ROOT = configure()

REQUIRED_INPUT_COLUMNS = [
    "repo_id",
    "instruction_file",
    "raw_reference",
    "resolved_path",
    "extraction_rule",
    "confidence",
]

REQUIRED_MANUAL_COLUMNS = [
    "manual_is_reference_correct",
    "manual_resolved_path_correct",
    "manual_should_be_used_for_scope",
    "manual_reference_category",
    "manual_notes",
    "annotator",
    "annotated_at",
]

MANUAL_FIELD_LABELS = [
    ("manual_is_reference_correct", "Is reference correct?"),
    ("manual_resolved_path_correct", "Is resolved path correct?"),
    ("manual_should_be_used_for_scope", "Use for scope?"),
    ("manual_reference_category", "Category"),
    ("manual_notes", "Notes"),
    ("annotator", "Annotator"),
    ("annotated_at", "Annotated at"),
]


def verify_columns(df: pd.DataFrame, csv_path: Path) -> None:
    missing_input = [c for c in REQUIRED_INPUT_COLUMNS if c not in df.columns]
    missing_manual = [c for c in REQUIRED_MANUAL_COLUMNS if c not in df.columns]
    if missing_input or missing_manual:
        parts: list[str] = []
        if missing_input:
            parts.append(f"missing input columns: {', '.join(missing_input)}")
        if missing_manual:
            parts.append(f"missing manual columns: {', '.join(missing_manual)}")
        raise SystemExit(f"{csv_path}: {'; '.join(parts)}")


def _escape_md(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def render_markdown(df: pd.DataFrame, source_csv: str) -> str:
    lines: list[str] = [
        "# Co-change reference validation sample (annotation workbook)",
        "",
        f"Source CSV: `{source_csv}`",
        "",
        "Guidelines: `annotation/cochange_reference_validation_guidelines.md`",
        "",
        "Schema: `annotation/cochange_reference_validation_schema.md`",
        "",
        "**Do not edit this file for annotation.** Fill the CSV and re-run "
        "`make prepare-reference-validation` to refresh this view.",
        "",
        f"Total rows: **{len(df)}**",
        "",
    ]

    grouped = df.sort_values(["repo_id", "instruction_file"]).groupby(
        ["repo_id", "instruction_file"], sort=False
    )

    for (repo_id, instruction_file), group in grouped:
        lines.extend(
            [
                f"## `{repo_id}` — `{instruction_file}`",
                "",
                f"Rows in this group: {len(group)}",
                "",
            ]
        )
        for idx, row in group.iterrows():
            row_num = int(idx) + 2  # header + 1-based CSV line hint
            lines.extend(
                [
                    f"### Row {row_num}",
                    "",
                    "| Field | Value |",
                    "|-------|-------|",
                    f"| Raw reference | `{_escape_md(row['raw_reference'])}` |",
                    f"| Resolved path | `{_escape_md(row['resolved_path'])}` |",
                    f"| Extraction rule | `{_escape_md(row['extraction_rule'])}` |",
                    f"| Confidence | `{_escape_md(row['confidence'])}` |",
                    "",
                    "**Manual annotation (fill in CSV):**",
                    "",
                ]
            )
            for col, label in MANUAL_FIELD_LABELS:
                value = row.get(col, "")
                display = "" if pd.isna(value) or str(value).strip() == "" else str(value)
                lines.append(f"- **{label}** (`{col}`): {display or '_(empty)_'}")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=ROOT / "annotation/cochange_reference_validation_sample.csv",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "annotation/cochange_reference_validation_sample.md",
    )
    args = parser.parse_args()

    if not args.input.is_file():
        raise SystemExit(f"Input not found: {args.input}")

    df = pd.read_csv(args.input, dtype=str, keep_default_na=False)
    verify_columns(df, args.input)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    source_label = str(args.input)
    try:
        source_label = str(args.input.resolve().relative_to(ROOT.resolve()))
    except ValueError:
        pass
    args.output.write_text(render_markdown(df, source_label), encoding="utf-8")

    print(f"verified columns in {args.input}")
    print(f"wrote {args.output} ({len(df)} rows, {df.groupby(['repo_id', 'instruction_file']).ngroups} groups)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
